#!/bin/bash

testdir=$(dirname $0)

if [ -z "$PYLINTRC" ]
then
  export PYLINTRC=$testdir/extras/pylintrc
fi

highest=0

# find all tests
# use different invocations--first is BSD, second is GNU
alltests=$(find $testdir -maxdepth 1 -type f -perm +0111) || alltests=$(find $testdir -maxdepth 1 -type f -perm /0111)
for script in $alltests
do
  # skip self and 'todos' 
  if [ $script == $0 -o $script == "$testdir/todos" ]
  then
    continue
  fi

  echo "=========== $script beginning ===================================="
  $script
  rc=$?
  echo "            $script finished; rc=$rc"

  if [ $rc -gt $highest ]
  then
    highest=$rc
  fi

done

if [ $highest -gt 0 ]
then
  echo "=========== Errors occurred, highest return value is $highest"
fi
exit $highest
