#!/bin/bash

testdir=$(dirname $0)

if [ -z "$PYLINTRC" ]
then
  export PYLINTRC=$testdir/extras/pylintrc
fi

highest=0

# determine executability predicate
if find --version >/dev/null 2>&1
then
  IS_EXECUTABLE="-executable"
else
  IS_EXECUTABLE="-perm +0111"
fi

# find all tests
alltests=$(find $testdir -maxdepth 1 -type f $IS_EXECUTABLE 2>/dev/null)

# if no tests found, that's probably an issue
if [ -z "$alltests" ]
then
  echo "No tests found" >&2
  exit 1
fi

# defaults
lsstaged() {
  #git status --porcelain | grep '^[AM]' | awk '{print $2}'
  #git status --porcelain | awk '$1 ~ /^\[AM\]/ {print $2}'
  git diff --cached --name-only --diff-filter=ACM
}
lsfiles="git ls-files"

# process command-line arguments
case "$1" in
  --staged)
    lsfiles=lsstaged
    ;;
esac

# execute tests
for script in $alltests
do
  # skip self and 'todos' 
  if [ $script == $0 -o $script == "$testdir/todos" ]
  then
    continue
  fi

  echo "=========== $script beginning ===================================="
  $lsfiles | $script
  rc=$?
  echo "            $script finished; rc=$rc"

  if [ $rc -gt $highest ]
  then
    highest=$rc
  fi

done

if [ $highest -gt 0 ]
then
  echo "=========== Errors occurred, highest return value is $highest"
fi
exit $highest
