#!/bin/bash

testdir=$(dirname $0)

highest=0

# find all tests
for script in $(find $testdir -maxdepth 1 -type f -perm +0111)
do
  # skip self and 'todos' 
  if [ $script == $0 -o $script == "$testdir/todos" ]
  then
    continue
  fi

  echo "=========== $script beginning ===================================="
  $script
  rc=$?
  echo "            $script finished; rc=$rc"

  if [ $rc -gt $highest ]
  then
    highest=$rc
  fi

done

if [ $highest -gt 0 ]
then
  echo "=========== Errors occurred, highest return value is $highest"
fi
exit $highest
