#!/bin/sh

pattern="TODO:"

if git grep "$pattern"
then
  todos=$(git grep -c "$pattern" | awk -F: 'BEGIN { count = 0 } { count += $2 } END { print count }')
  echo "There are $todos TODO notes in repository"
fi

exit $todos
